
CC := $(CROSS_COMPILE)gcc

SRCS =\
aesdsocket.c\
connectionlist.c\
timestampThread.c\
connectionHandlerThread.c\
connectionReceiverThread.c\


OBJS = $(SRCS:.c=.o)

all: aesdsocket

aesdsocket: $(OBJS)
	$(CC) $(OBJS) -o aesdsocket -lpthread

$(TARGET).o: $(TARGET).c
	$(CC) -c $(TARGET).c -o $(TARGET).o -O0 -g3

clean:
	rm -rf aesdsocket
	rm -rf *.o
	
